### ISSUE TITLE
No error handling for `fs.statSync` call

### ISSUE THREAD

**Issue by jdanford** [itsahappymedium/dude-wheres-my-hd#1]
Errors returned from `fs.statSync(...)` cause `dude-wheres-my-hd` to fail hard. For example, I get the following error due to a broken symlink: `Error: ENOENT: no such file or directory, stat './.byobu/.ssh-agent'`. Would you rather silently ignore these errors, or log them and continue?

**Comment by kodie** [comment]
Ah, good catch! I'd say log them and continue would probably be the best.
